### PR TITLE
Fix requireModule testing of versions on PS v3.

### LINKED ISSUE #215: Invoke-Plaster fails at the end of scaffolding on PowerShell 3.0
Just ran Plaster to scaffold a project using the built-in template on PS 3.0, here's the output:

```
  ____  _           _
 |  _ \| | __ _ ___| |_ ___ _ __
 | |_) | |/ _` / __| __/ _ \ '__|
 |  __/| | (_| \__ \ ||  __/ |
 |_|   |_|\__,_|___/\__\___|_|
                                            v1.0.0
==================================================
Enter the name of the module: MyNewModule
Enter the version number of the module (0.1.0): 

Create test dir and add Pester test for module manifest validation:
[N] No [Y] Yes [?] Help (default is "No"):

Select a editor for editor integration (or None):
[N] None [C] Visual Studio Code [?] Help (default is "None"):

Scaffolding your PowerShell Module...

   Create MyNewModule.psd1
   Create MyNewModule.psm1
   Create test\MyNewModule.Tests.ps1
   Create .vscode\settings.json
   Create .vscode\tasks.json
A parameter cannot be found that matches parameter name 'FullyQualifiedName'.
```

Almost worked ;)

### PR DESCRIPTION
**Pull request by rkeithhill**
Fix #215.

Quick checked on v3.

### CODE REVIEW

**Comment by rkeithhill** [comment]
BTW I don't have V4 handy.  Can you check of the `FullyQualifiedName` parameter is available on v4?  If it is not, then I will need to tweak the PS version checks in the PR.

**Comment by daviwil** [comment]
Yep, it's there:

```
PS C:\Users\daviwil> Get-Help Get-Module -Parameter FullyQualifiedName

-FullyQualifiedName <ModuleSpecification[]>

    Required?                    false
    Position?                    Named
    Accept pipeline input?       true (ByPropertyName)
    Parameter set name           Loaded, PsSession, CimSession, Available
    Aliases                      None
    Dynamic?                     false
```

**Comment by daviwil** [comment]
Just tried it out on the PSv3 machine, it works!  Thanks for the quick fix

**Comment by rkeithhill** [comment]
This sort of incompatibility (missing parameter) is tougher to anticipate.  Sure wish PSSA could let me tell it I wanted to support v3 and higher and then flag me on things that aren't supported in the various versions I want to support.

**Comment by daviwil** [comment]
Yep, we're planning to add that at some point in the near future :)

**Pull request merged**
