### PR TITLE
Refactored psake build script.

### PR DESCRIPTION
**Pull request by rkeithhill**
This separates out the user customizations into a separate file build.settings.ps1.  Also made changes related to the discussion in issue #145. Fixed some bugs with the build script as well after a fair bit of testing.  Too bad my code-signing cert expired last month. Hopefully DigiCert will come through with a new cert so I can test the Sign task.

### CODE REVIEW

**Comment by rkeithhill** [comment]
Ugh, by splitting out the psake properties (variables) from where they are mostly used, I wind up with 14 PSSA warnings in a newly scaffolded module.  I can eliminate the warnings like this:
```powershell
    [System.Diagnostics.CodeAnalysis.SuppressMessage('PSUseDeclaredVarsMoreThanAssigments', '', Scope='*', Target='DocsRootDir')]
    $DocsRootDir = "$PSScriptRoot/docs"
    $SrcRootDir  = "$PSScriptRoot/src"
    [System.Diagnostics.CodeAnalysis.SuppressMessage('PSUseDeclaredVarsMoreThanAssigments', '', Scope='*', Target='TestRootDir')]
    $TestRootDir = "$PSScriptRoot/test"
```
but that is a bit of a spew.  I wish there was a way to tell PSSA that the file always gets dot sourced and to never evaluate the file by itself.

**Comment by daviwil** [comment]
@kapilmb has started improving Script Analyzer to make certain rules (recently the one about ShouldProcess usage) have more awareness of the context or usage of certain things before giving warnings about them.  I think we'll continue to move in that direction to make the rules smarter so it's good to know that this is a case where a rule can be improved with that kind of logic.

**Comment by rkeithhill** [comment]
I saw that PSSA issue get closed. Way cool.  Looks like the code to fix it was non-trivial.

**Comment by daviwil** [comment]
Yep, we're finally starting to put the "Analyzer" into "Script Analyzer" ;)

**Comment by rkeithhill** [comment]
BTW I was able to run through all the build script tasks up to sign/buildhelp/install with no problems.  Haven't tested publish yet.  Do you have a private test gallery that we could use for testing the publish task?

**Comment by daviwil** [comment]
Not one that's publicly available, but I wonder if we could easily set one up with [PSPrivateGallery](https://github.com/PowerShell/PSPrivateGallery).  Also wonder if we could somehow set up a private gallery inside of an AppVeyor VM...

**Pull request merged**
