### PR TITLE
Skip script analysis without PSSA installed.

### PR DESCRIPTION
**Pull request by davegreen**
Fixes the issue where the build fails if PSSA is not installed.

Also adds a warning/verify to the NewModule manifest for PSSA.

### CODE REVIEW

**Comment by davegreen** [comment]
Aah, ok, good point. I always seem to default to doing things the hard way :P

**Comment by davegreen** [comment]
That makes sense, I'll do that.

OK, yeah, I was in two minds about how it read, but more relevant info is better.

**Comment by rkeithhill** [comment]
BTW this build script is really taking shape. Starting to feel pretty solid. Thanks for your efforts on this puppy!!

**Comment by davegreen** [comment]
That should be good. I renamed the PSSA control options at the same time. 

Yeah, it's definitely looking good. Thank you for your input!

**Comment by daviwil** [comment]
Nice work Dave, this is great!

**Pull request merged**
