### PR TITLE
expanded modulemanifest creation 

### PR DESCRIPTION
**Pull request by bgelens**
to include PowerShellVersion, NestedModules and DscResourcesToExport properties.

### CODE REVIEW

**Comment by daviwil** [comment]
Hey Ben, thanks for the PR!  The only feedback I have is to make sure the new schema fields have the right camel casing, `powerShellVersion`, `nestedModules`, and `dscResourcesToExport`.  Otherwise looks good to me!

**Comment by daviwil** [comment]
@rkeithhill, Ben asked me if there's a way to make additive changes to an existing module manifest field so that new values can be added to it (like for `DscResourcesToExport`).  Do we support that in any way right now?

**Comment by bgelens** [comment]
these includes are fine for initial creation of a Dsc Resource Modules but if later we want to add additional resources to an existing module. It would be best if we could run custom code like Update-ModuleManifest.

My plan is to have a NewDscResourceModule template which scaffolds a new Module including a first resource. Then have a second template AddDscResourceToModule which adds additional resources.
A couple of conditions would need to be evaluated. E.g. if the first Resource was MOF schema base and the second is Class, the PowerShellVersion would need to be bumped from 4.0 to 5.1 and NestedModules + DscResourcesToExport need to have additional entries without removing existing once

**Comment by bgelens** [comment]
@daviwil Fixed the casing (I think)

**Comment by daviwil** [comment]
Casing looks perfect now!

**Comment by rkeithhill** [comment]
@daviwil That's the way the newModuleManifest directive works:
```posh
# If there is an existing module manifest, load it so we can reuse old values not specified by
# template.
```

**Comment by rkeithhill** [comment]
The AppVeyor build failure seems to be  due to an upload failure at the end of the build/test.  As for Travis, we don't have a Travis config file yet AFAICT.

**Comment by daviwil** [comment]
Yeah, dunno what's going on with AppVeyor.  I know that @PowerSchill wants to submit the travis.yml for Plaster, I had turned on Travis on this repo in anticipation of that.  I'm not worried about the current failures so I'll go ahead and merge it :)

**Comment by rkeithhill** [comment]
@bgelens Thanks man!

**Comment by zloeber** [comment]
I'm a bit curious why not the consideration for merging #252 instead? It covers pretty much every module manifest property in a bit more of a dynamic manner. It covers every parameter that new-modulemanifest has now (and in the future) for retaining existing manifest settings as well.

**Comment by bgelens** [comment]
@rkeithhill Thanks! About the update process of an existing manifest: What is not currently covered are manifest properties which can have multiple values (I think). DscResourcesToExport for example shouldn't per se replace the existing value but maybe inquiry the user to add / replace?

@zloeber I didn't look for other PRs, sorry! :( I was just busy creating a template and this was blocking me from advancing.

**Pull request merged**
