### PR TITLE
Remove condition attribute on choice.

### PR DESCRIPTION
**Pull request by rkeithhill**
Not ready to add condition attribute on `<choice>` just yet.  More works needs to be done to figure out how to make the <parameter default attribute work ocrrectly in face of dynamic list of choices.

Add Pester test for parameter condition attribute.
Fix Test task in tasks.json by temporarily replacing ${env.windir} with C:\\Windows. This seems to be a regression in VSCode.

### CODE REVIEW

**Comment by rkeithhill** [comment]
Looks like we need to add a travis file at some point.

**Comment by PowerSchill** [comment]
I took a look at travis initially but apparently psake has an issue with non-windows environments. I can try and take another look at it.

**Comment by rkeithhill** [comment]
Do you remember what the issue was?  David and I are now maintainers on psake (I think) and maybe we could fix it.

**Comment by PowerSchill** [comment]
It complains about not being able to find .NET and judging by the code its strictly targeted to Windows only. 
```powershell
$frameworkDirs = @()
    if ($buildToolsVersions -ne $null) {
        foreach($ver in $buildToolsVersions) {
            if (Test-Path "HKLM:\SOFTWARE\Microsoft\MSBuild\ToolsVersions\$ver") {
                $frameworkDirs += (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\MSBuild\ToolsVersions\$ver" -Name $buildToolsKey).$buildToolsKey
            }
        }
    }
    $frameworkDirs = $frameworkDirs + @($versions | foreach { "$env:windir\Microsoft.NET\$bitness\$_\" })
```

**Comment by PowerSchill** [comment]
Here is an issue reference. https://github.com/psake/psake/issues/197. And it looks like someone already has a pull request waiting https://github.com/psake/psake/pull/198

**Comment by larssb** [comment]
+1 for really wanting MacOS and Linux support for Psake, now that we have PowerShell core on other OS flavors than Windows.

Thank you 👍

**Pull request merged**
